services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./test_project:/test_project
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
      - "5435:5432"
    volumes:
      - ./dbdata/db:/var/lib/postgresql/data/

      
      