# Generated by Django 4.2.7 on 2023-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', 'USA'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='USD', verbose_name='Валюта')),
                ('stripe_product_id', models.CharField(blank=True, editable=False)),
                ('stripe_price_id', models.CharField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Тоовар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('order_details', models.JSONField(default=dict, verbose_name='Спецификация')),
                ('item', models.ManyToManyField(related_name='orders', to='stripe_api.item')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
